{{- range .Values.global.tenants -}}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tenant-{{ .name }}
  namespace: tenant-{{ .name }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant-{{ .name }}",
      "type": "ovn-k8s-cni-overlay",
      "topology":"localnet",
      "vlanID": {{ .vlanID }},
      "subnets": "{{ .cidr }}",
      "physicalNetworkName": "tenant-{{ .name }}",
      "netAttachDefName": "tenant-{{ .name }}/tenant-{{ .name }}"
    }
{{- end -}}